In [ ]:
# import panda library:
import pandas as pd

## Series in pandas:
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.
general syntax : Series() : first letter S must be capital.

In [2]:
dic={
    "name":["tahseen","yasir","noman","haroon"],
    "roll-no":[18,21,17,19]
}
new=pd.Series(dic)
print(new)

name       [tahseen, yasir, noman, haroon]
roll-no                   [18, 21, 17, 19]
dtype: object

### indexing in series:
indexing will be automitically start from 0 upto n: 
the value can be acceess through index number:
syntax : name [index number].
we can aslo give a random values to index:

In [15]:
dic={
    "name":["tahseen","yasir","noman","haroon"],
    "roll-no":[18,21,17,19]
}
new=pd.Series(dic)
# accessing the insex 1 value:
print(new[1])
# taking a ist of three numbers:
list=[1,2,3]
# assiging index values x,y,z to values:
new=pd.Series(list,index=["x","y","z"])
print(new["x"])

[18, 21, 17, 19]
1

C:\Users\Haris\AppData\Local\Temp\ipykernel_13480\4194566998.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(new[1])

### DataFrame in pandas:
Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

In [3]:
dic={
    "name":["tahseen","yasir","noman","haroon"],
    "roll-no":[18,21,17,19]
}
new=pd.DataFrame(dic)
print(new)

      name  roll-no
0  tahseen       18
1    yasir       21
2    noman       17
3   haroon       19

### accesing values in dataframes:
we will acces values through several ways but if we want to access 
one row in table then will use loc() function>
## syntax
loc[index number]

In [33]:
dic={
    "name":["tahseen","yasir","noman","haroon"],
    "roll-no":[18,21,17,19],
    "subjects":["python","web dev","DBMS","digital marketting"]
}
new=pd.DataFrame(dic)
# we want to access the second row :
print(new.loc[2])
# but in this method the output will be in series form.

# similarly if we want t0 access multiple values at a same time.

print(new.loc[[0,2]])
#same as a series we can a give our own values as a index:
new=pd.DataFrame(dic,index=["a","b","c","d"])
print(new)
print (new.loc["c"])

name        noman
roll-no        17
subjects     DBMS
Name: 2, dtype: object
      name  roll-no subjects
0  tahseen       18   python
2    noman       17     DBMS
      name  roll-no            subjects
a  tahseen       18              python
b    yasir       21             web dev
c    noman       17                DBMS
d   haroon       19  digital marketting
name        noman
roll-no        17
subjects     DBMS
Name: c, dtype: object

## load CSV file
A simple way to store big data sets is to use CSV files (comma separated files).

CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
## syntax:
name=pd.read("CSV file")

In [10]:
import pandas as pd
# this will load CSV file.
file=pd.read_csv('data.csv')
# this fuction is used to output the values:
#print(file.to_string)

# head is used to output the first 5 rows by default.
# head (size) if we want to out our own chice rows then will enter the size.
print(file.head())
print(file.head(10))
# tail(size): functionality is same as head() but will out the values from the last rows in reverse orderd.
print(file.tail())

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0
    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
# to get info about the data info()function will be used:
print(file.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
None

## above output info:
in above output it is shown that there is total 32 rows and 5 colums.
and same as shown not null values in each colums.

## cleaning of data:
Data cleaning means fixing bad data in your data set.

Bad data could be:

1.Empty cells
2.Data in wrong format
3.Wrong data
4.Duplicates

## Empty Cells
Empty cells can potentially give you a wrong result when you analyze data.

Remove Rows
One way to deal with empty cells is to remove rows that contain empty cells.

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.

In [26]:
# simple we output the data set:
print(file.to_string)
# we have a null cells in 18,23,28 position and we want to remove these rows:
# so we will use dropna() function.
# inplace = true : it means to returns the new update dataframe.
## file.dropna(inplace=True)
file

<bound method DataFrame.to_string of     Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0>

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## replace Empty Values
Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:

In [22]:
# if we want to insert 300 in 18 row empty cell then will use:
file.fillna({"Duration":300})
file

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Replace Using Mean, Median, or Mode
A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column: