## NAME : TAHSEEN ULLAH
## STUDENT OF : BS COMPUTER SCIENCE %TH SEMESTER
## COUNTRY : PAKISTAN
## SMALL_PROJECT : PATIENTS RECORD
## DATED : 19/12/2025

first we will import pandas library.

In [66]:
import pandas as pd

In [ ]:
# load dataset :
patients=pd.read_csv("hospital_patients.csv")

In [ ]:
# Show the datas
patients.head(10)

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,ali,M,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,SARA,F,-30,05/02/2024,NaN,cardiology,Karachi,3000
2,102,SARA,female,30,05/02/2024,NaN,Cardiology,Karachi,"$3,000"
3,103,john doe,m,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,F,twenty,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,ahmed,NaN,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,ZARA,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,usman,M,-5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,f,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [ ]:

patients.describe()

       patient_id
count   10.000000
mean   104.700000
std      2.750757
min    101.000000
25%    102.250000
50%    104.500000
75%    106.750000
max    109.000000

In [ ]:
# shows information about dataset
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      10 non-null     int64
 1   name            10 non-null     object
 2   gender          9 non-null      object
 3   age             10 non-null     object
 4   admission_date  10 non-null     object
 5   discharge_date  7 non-null      object
 6   department      10 non-null     object
 7   city            7 non-null      object
 8   bill_amount     10 non-null     object
dtypes: int64(1), object(8)
memory usage: 852.0+ bytes

In [ ]:
# to shows missing null values
patients.isnull()

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False
6,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,True,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False

In [ ]:
# drop the duplicated values first.
patients.duplicated()
patients=patients.drop_duplicates(["patient_id"])
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,ali,M,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,SARA,F,-30,05/02/2024,NaN,cardiology,Karachi,3000
3,103,john doe,m,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,F,twenty,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,ahmed,NaN,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,ZARA,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,usman,M,-5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,f,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [ ]:
# write the names in sentence format
patients["name"]=patients["name"].str.strip().str.capitalize()
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,M,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,F,-30,05/02/2024,NaN,cardiology,Karachi,3000
3,103,John doe,m,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,F,twenty,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,Ahmed,NaN,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,Usman,M,-5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,f,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [ ]:
# distinct word used for male and female as there was multiplenames used for male and female.
patients["gender"].unique()
patients["gender"]=patients["gender"].replace({"M":"male","m":"male","F":"female","f":"female"})
patients["gender"]=patients["gender"].fillna("male")
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,-30,05/02/2024,NaN,cardiology,Karachi,3000
3,103,John doe,male,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,female,twenty,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,Usman,male,-5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [ ]:
# convert the age column to numeric format.
patients["age"]=pd.to_numeric(patients["age"],errors="coerce")
# remove the negative sign as the age must be positive.
patients["age"]=patients["age"].abs()
# fill the missing values using mean.
age_mean=patients["age"].mean()
patients["age"]=patients["age"].fillna(age_mean)
#round the values to int format from float 
patients["age"]=patients["age"].round().astype(int)
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,30,05/02/2024,NaN,cardiology,Karachi,3000
3,103,John doe,male,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,Usman,male,5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [ ]:
# the date have mixed and multiple format. so we will convert into one single format.
patients['admission_date']=pd.to_datetime(patients["admission_date"] ,format='mixed')
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,30,2024-05-02,NaN,cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,cardiology,NaN,"$6,500"
7,107,Usman,male,5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,cardiology,NaN,5000

In [ ]:
# convert Discharge_date into datetime format from string.
patients['discharge_date']=pd.to_datetime(patients['discharge_date'])
# we have 2 missing values and observing from other data there is 5 days difference between admission_date 
# discharge date so we fill the missing values by adding 5 days to discharge_date.
patients.loc[patients['discharge_date'].isna(),"discharge_date"] =(
    patients.loc[patients['discharge_date'].isna(),"admission_date"]+pd.Timedelta(days=5))
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,cardiology,NaN,"$6,500"
7,107,Usman,male,5,2024-07-20,2024-07-25,neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,cardiology,NaN,5000

In [ ]:
patients['department'].unique()
# set departments name into sentence format where first letter will be capital and other will be small.
patients['department']=patients['department'].str.strip().str.capitalize()
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,Cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,Orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,Cardiology,NaN,"$6,500"
7,107,Usman,male,5,2024-07-20,2024-07-25,Neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,Cardiology,NaN,5000

In [ ]:
# we have don't idea about city and we cannot fill randomly or using mode so we set
# it to unknown.
patients['city'].fillna('unknown',inplace=True)
patients

C:\Users\Haris\AppData\Local\Temp\ipykernel_3128\3273053395.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  patients['city'].fillna('unknown',inplace=True)

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,Cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,unknown,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,Orthopedics,Islamabad,"$5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,Cardiology,unknown,"$6,500"
7,107,Usman,male,5,2024-07-20,2024-07-25,Neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,Cardiology,unknown,5000

In [ ]:
# there is dollar sign involoves so simply we remove the dollar sign.
patients['bill_amount']=patients['bill_amount'].str.replace("$",'',regex=False)
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,Cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,unknown,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,Orthopedics,Islamabad,"5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,Cardiology,unknown,"6,500"
7,107,Usman,male,5,2024-07-20,2024-07-25,Neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,Cardiology,unknown,5000

In [ ]:
# the index was inconsistent 2 was missing so we reset the index.
patients.reset_index(drop=True,inplace=True)
patients

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,Cardiology,Karachi,3000
2,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,unknown,4500
3,104,Fatima,female,36,2024-04-01,2024-04-05,Orthopedics,Islamabad,"5,000"
4,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
5,106,Zara,male,60,2024-06-15,2024-06-20,Cardiology,unknown,"6,500"
6,107,Usman,male,5,2024-07-20,2024-07-25,Neurology,Karachi,3500
7,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"4,200"
8,109,Noor,female,50,2024-01-09,2024-09-10,Cardiology,unknown,5000

## finally we clean , manipulate the dataset for use.

In [90]:
patients.to_csv("update_hospital.csv",index=False)

In [ ]:
# BEFORE:
before=pd.read_csv("hospital_patients.csv")
before

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,ali,M,25,2024-01-05,2024-01-10,Cardiology,Lahore,"$2,500"
1,102,SARA,F,-30,05/02/2024,NaN,cardiology,Karachi,3000
2,102,SARA,female,30,05/02/2024,NaN,Cardiology,Karachi,"$3,000"
3,103,john doe,m,40,2024.03.10,2024-03-15,Neurology,NaN,4500
4,104,Fatima,F,twenty,2024-04-01,2024-04-05,orthopedics,Islamabad,"$5,000"
5,105,ahmed,NaN,35,2024/05/15,2024-05-20,Orthopedics,Lahore,4000
6,106,ZARA,male,60,15-06-2024,2024-06-20,cardiology,NaN,"$6,500"
7,107,usman,M,-5,2024-07-20,NaN,neurology,Karachi,3500
8,108,Hassan,f,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"$4,200"
9,109,noor,female,50,01-09-2024,2024-09-10,cardiology,NaN,5000

In [85]:
# AFTER
after=patients
after

,patient_id,name,gender,age,admission_date,discharge_date,department,city,bill_amount
0,101,Ali,male,25,2024-01-05,2024-01-10,Cardiology,Lahore,"2,500"
1,102,Sara,female,30,2024-05-02,2024-05-07,Cardiology,Karachi,3000
3,103,John doe,male,40,2024-03-10,2024-03-15,Neurology,unknown,4500
4,104,Fatima,female,36,2024-04-01,2024-04-05,Orthopedics,Islamabad,"5,000"
5,105,Ahmed,male,35,2024-05-15,2024-05-20,Orthopedics,Lahore,4000
6,106,Zara,male,60,2024-06-15,2024-06-20,Cardiology,unknown,"6,500"
7,107,Usman,male,5,2024-07-20,2024-07-25,Neurology,Karachi,3500
8,108,Hassan,female,45,2024-08-01,2024-08-07,Orthopedics,Lahore,"4,200"
9,109,Noor,female,50,2024-01-09,2024-09-10,Cardiology,unknown,5000