## Name : Tahseen ullah
## Student : computer science 
## institute : GDC totakan
## project : data analysis and cleaning with pandas
## Dated : 15/12/2025

In [61]:
# import pandas library.
import pandas as pd

we have a dataset which include some missing, wrong, wrong format values.

In [62]:
# load a dataset 
df=pd.read_csv("dumy.csv")
df

     id    name  age  gender salary
0     1     Ali   25    Male  50000
1     2    Sara  NaN  Female  60000
2     3   Ahmed   -3       M    abc
3     4  Ayesha   30  Female  70000
4     5     Ali   25    Male  50000
..  ...     ...  ...     ...    ...
95   96    Zara   27  Female  58000
96   97  Hassan   42    Male  69000
97   98    Iqra  NaN  Female  67000
98   99     Ali   25    Male  50000
99  100    Sara   29  Female  61000

[100 rows x 5 columns]

In [63]:
# we need information about data such as columns , rows, null values datatype etc.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int64
 1   name    99 non-null     object
 2   age     83 non-null     object
 3   gender  100 non-null    object
 4   salary  94 non-null     object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

In [64]:
# before applying we need to know as there as duplicated values or not.
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [65]:
# to know which cell contain null values.
df.isnull()

       id   name    age  gender  salary
0   False  False  False   False   False
1   False  False   True   False   False
2   False  False  False   False   False
3   False  False  False   False   False
4   False  False  False   False   False
..    ...    ...    ...     ...     ...
95  False  False  False   False   False
96  False  False  False   False   False
97  False  False   True   False   False
98  False  False  False   False   False
99  False  False  False   False   False

[100 rows x 5 columns]

In [66]:
# there is no name in 8 location record so we will delete it.
df=df.drop(8)
df
# we need to remove duplicated values.
df=df.drop_duplicates()
df

     id    name  age  gender salary
0     1     Ali   25    Male  50000
1     2    Sara  NaN  Female  60000
2     3   Ahmed   -3       M    abc
3     4  Ayesha   30  Female  70000
4     5     Ali   25    Male  50000
..  ...     ...  ...     ...    ...
95   96    Zara   27  Female  58000
96   97  Hassan   42    Male  69000
97   98    Iqra  NaN  Female  67000
98   99     Ali   25    Male  50000
99  100    Sara   29  Female  61000

[99 rows x 5 columns]

In [80]:
# in age column there is some values in string format so we convert it into numeric type.
df["age"]=df["age"].replace({"twenty":20,"twenty five":25})

# after that there is some values which do not make sense such as abc,?,missing etc.
# so we convert the column into numeric type in which the data which not make a sense become 
# null or missing. 
df["age"]=pd.to_numeric(df["age"],errors="coerce")
print(df["age"].dtype)

float64

In [ ]:
# after that there is age with negative values which is wrong so we make it positive.
df["age"]=df["age"].abs()
# after that there is some people age is showing below 10 so we ind the mean and 
# replace the of which is less than 10 by its mean. 
x=df["age"].mean()
df.loc[df["age"]<10, "age"]=x
df
# the age which contain null values will be fill by its mean.
age=df["age"].mean()
df["age"]=df["age"].fillna(age).astype(int)

C:\Users\Haris\AppData\Local\Temp\ipykernel_4084\176559793.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '31.343434343434343' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df["age"]<10, "age"]=x

     id    name   age  gender  salary
0     1     Ali  25.0    Male   50000
1     2    Sara  31.0  Female   60000
2     3   Ahmed  29.0    Male   65659
3     4  Ayesha  30.0  Female   70000
4     5     Ali  25.0    Male   50000
..  ...     ...   ...     ...     ...
94   96    Zara  27.0  Female   58000
95   97  Hassan  42.0    Male   69000
96   98    Iqra  31.0  Female   67000
97   99     Ali  25.0    Male   50000
98  100    Sara  29.0  Female   61000

[99 rows x 5 columns]

In [82]:
# convert salary column into numeric format.
df["salary"]=pd.to_numeric(df["salary"],errors="coerce")
# filling null values in salary clumn by its mean.
salary=df["salary"].mean()
df["salary"]=df["salary"].fillna(salary).astype(int)
df

     id    name   age  gender  salary
0     1     Ali  25.0    Male   50000
1     2    Sara  31.0  Female   60000
2     3   Ahmed  29.0    Male   65659
3     4  Ayesha  30.0  Female   70000
4     5     Ali  25.0    Male   50000
..  ...     ...   ...     ...     ...
94   96    Zara  27.0  Female   58000
95   97  Hassan  42.0    Male   69000
96   98    Iqra  31.0  Female   67000
97   99     Ali  25.0    Male   50000
98  100    Sara  29.0  Female   61000

[99 rows x 5 columns]

In [73]:
# finding all unique values in gender column.
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [83]:
# as there is only two values are wrong so replace by it correct name.
df["gender"]=df["gender"].replace({"M":"Male","F":"Female"})

In [74]:
# as we was removed row 8 so the index was become inconsistent so we will make 
#it consistent again.
df.reset_index(drop=True,inplace=True)
df

     id    name   age  gender  salary
0     1     Ali  25.0    Male   50000
1     2    Sara  31.0  Female   60000
2     3   Ahmed  29.0    Male   65659
3     4  Ayesha  30.0  Female   70000
4     5     Ali  25.0    Male   50000
..  ...     ...   ...     ...     ...
94   96    Zara  27.0  Female   58000
95   97  Hassan  42.0    Male   69000
96   98    Iqra  31.0  Female   67000
97   99     Ali  25.0    Male   50000
98  100    Sara  29.0  Female   61000

[99 rows x 5 columns]

In [ ]:
# old file before cleaning.
old_file=pd.read_csv("dumy.csv")
old_file

     id    name  age  gender salary
0     1     Ali   25    Male  50000
1     2    Sara  NaN  Female  60000
2     3   Ahmed   -3       M    abc
3     4  Ayesha   30  Female  70000
4     5     Ali   25    Male  50000
..  ...     ...  ...     ...    ...
95   96    Zara   27  Female  58000
96   97  Hassan   42    Male  69000
97   98    Iqra  NaN  Female  67000
98   99     Ali   25    Male  50000
99  100    Sara   29  Female  61000

[100 rows x 5 columns]

In [87]:
# new file after cleaning.
df

     id    name   age  gender  salary
0     1     Ali  25.0    Male   50000
1     2    Sara  31.0  Female   60000
2     3   Ahmed  29.0    Male   65659
3     4  Ayesha  30.0  Female   70000
4     5     Ali  25.0    Male   50000
..  ...     ...   ...     ...     ...
94   96    Zara  27.0  Female   58000
95   97  Hassan  42.0    Male   69000
96   98    Iqra  31.0  Female   67000
97   99     Ali  25.0    Male   50000
98  100    Sara  29.0  Female   61000

[99 rows x 5 columns]